### ISSUE TITLE
Rebooting fails with LA57 and hypervisor-fw

### ISSUE THREAD

**Issue by sboeuf** [cloud-hypervisor/rust-hypervisor-firmware#140]
Reboot does not work on a machine with 5 level page table when Cloud Hypervisor is booted with `hypervisor-fw` (0.3.1).
It does work with direct kernel boot though.

The guest image version is Hirsute Hippo cloud image (21.04), including a 5.11 kernel. The kernel used for direct kernel boot is a 5.12 kernel coming from the branch `ch-5.12` from `cloud-hypervisor/linux`.

**Comment by muhamadazmy** [comment]
I have the same issue with latest hypervisor-fw release and also latest cloud-hypervisor. I am testing with `Ubuntu 20.04.4 LTS` power off terminates the cloud-hypervisor process, but when rebooting the VM is just stuck at 

```
[  OK  ] Reached target Reboot.
[   86.456476] reboot: Restarting system
```

I also notice an increase of host CPU usage (CPU is up to 110%) on a 12 core laptop

**Comment by retrage** [comment]
I'm interested in this issue, but I don't have access to the supported hardware. Rebooting works on the QEMU full emulated system with LA57 enabled `-cpu qemu64,+la57`. The guest image is Hirsute (21.04) cloud image.

**Comment by rbradford** [comment]
Thanks @retrage. I just tested (on an Ice Lake) with 22.04 (kernel 5.15) and the latest version of CH and rust-hypervisor-firmware and the reboot works fine.
