### ISSUE TITLE
Unable to build on intel machines.

### ISSUE THREAD

**Issue by rishirsinha** [cloud-hypervisor/rust-hypervisor-firmware#143]
After getting the latest nightly build I am still unable to build on linux machines.

I am getting the following:

note: instantiated into assembly here
  --> <inline asm>:53:10
   |
53 |     movw %ax, %ss
   |          ^

error: unknown token in expression

on every line of the assembly file. Is there something else I need to setup except for what I can see in the build scripts or the main page.

**Comment by retrage** [comment]
I made a quick fix.

**Comment by retrage** [comment]
@rishirsinha This is because default inline behavior has been changed in recent Rust nightly build. I committed the fix in PR #144. If you confirmed that it is fixed in the latest master branch, please close this issue.

**Comment by rishirsinha** [comment]
This did fix the issue.
