### ISSUE TITLE
Unable to build on arm64 devices.

### ISSUE THREAD

**Issue by rishirsinha** [cloud-hypervisor/rust-hypervisor-firmware#145]
It is not clear if the firmware is supported on linux or not. I have not found an arm build officially there. However, I attempted to build it on an arm machine and as I was worried it failed on the assembly code in ram32.s. I am building on arm64 using the nightly toolchain. I keep getting the following error for all commands:

error: instruction requires: Not 64-bit mode
    ljmpl $0x08, $rust64_start

**Comment by rbradford** [comment]
The firmware currently only supports x86_64.
