### ISSUE TITLE
NixOS with systemd-boot broken in v0.4

### ISSUE THREAD

**Issue by benmaddison** [cloud-hypervisor/rust-hypervisor-firmware#183]
This issue appears to have been introduced by 2e7e87b7.

NixOS, and probably other distros, place the full name of the default boot entry in the `default` option of `loader.conf`.

The above commit forcefully adds a further `.conf` to the name returned by `loader::default_entry_file()`, which results in `loader::load_default_entry()` attempting to open a bogus path such as `/loader/entries/foo.conf.conf`.

As far as I am aware, `/loader/loader.conf` is only a `systemd-boot` thing - i.e. it's not part of the [Boot Loader Spec], and is only defined in the [systemd manual].

According to that documentation, the `default` option should be handled as a glob pattern, to be matched against (presumably) the filenames in `/loader/entries/`.

I am happy to attempt a fix if others agree that this is a bug.

[Boot Loader Spec]: https://systemd.io/BOOT_LOADER_SPECIFICATION
[systemd manual]: https://www.freedesktop.org/software/systemd/man/loader.conf.html#

**Comment by rbradford** [comment]
@benmaddison Yes, please do open a PR if you can.

**Comment by benmaddison** [comment]
@rbradford ack, thanks. I will take a proper look later today.

**Comment by benmaddison** [comment]
@rbradford I have made a start on this, but have run into an issue I would appreciate some guidance on.

Based on the `systemd-boot` [docs](https://www.freedesktop.org/wiki/Software/systemd/systemd-boot/) and sources [here](https://github.com/systemd/systemd/blob/4885d7490b23e08d8444e5a68927ce9ce8727e5a/src/boot/efi/boot.c#L1666) and [here](https://github.com/systemd/systemd/blob/4885d7490b23e08d8444e5a68927ce9ce8727e5a/src/boot/efi/efi-string.c#L239), the pattern in the `default` option of `loader.conf` is matched against the whole filename of the entry - including the `.conf` extension.

Prior to #165, the comparison worked as if there was an implicit `*` at the end of the pattern, meaning pattern `foo` would successfully match `foo.conf`. This does not appear to be the case in the `systemd-boot` implementation.

Now, the problem is: the Clear Linux image used in the tests appears to rely on this implementation difference!

```
$  cat /mnt/loader/loader.conf | grep default
default Clear-linux-kvm-5.0.6-318
```
```
$  ls -l /mnt/loader/entries/
total 8
-rwxr-xr-x 1 root root 361 Apr  4  2019 Clear-linux-kvm-5.0.6-318.conf
```

I think that the reason this image works with `systemd-boot` (I assume - not having tried) is that there is only one entry, and that is used as a fallback.

It seems to me that there are 2 reasonable choices:
1. Implement the pattern match according to the `systemd-boot` implementation, *and* the fallback to a single entry so that we don't break boot for Clear Linux users; or
2. Implement the pattern match to re-try with an implicit `.conf` appended to the pattern if the first pass fails.

In my view option 2, although easier, creates an unwelcome divergence from `systemd-boot` which is likely to confuse users in future.

The primary downside to option 1 is that while booting the test image should still work, we will need a different example for the tests.

Please let me know your thoughts, before I go and waste time on an implementation that you can't accept.

**Comment by retrage** [comment]
I vote to option 1 because it will support both `systemd-boot` and Clear Linux environment without ad-hoc implementation. I think providing another boot image for testing the `systemd-boot` does not matter.

**Comment by benmaddison** [comment]
@retrage agreed. I have most of an implementation done, I'm just missing support for `[..]` matches - will put up a draft PR shortly.

**Comment by rbradford** [comment]
I thought Clear Linux was using systemd boot (but bear in mind our test image is very old) so maybe systemd-boot has changed behaviour.

**Comment by rbradford** [comment]
Hi @benmaddison, any update on this?

**Comment by benmaddison** [comment]
@rbradford apologies - got side tracked!

I have opened #188 as a draft, so that you can see progress so far.

Would like your opinion on the use of the `slice_take` feature. I can probably remove that if you prefer, at the expense of some readability and copying.

I will try and get it ready for a proper review in the next few days.
