### ISSUE TITLE
Guest os can't boot from spdk bdev

### ISSUE THREAD

**Issue by maydaycc** [cloud-hypervisor/rust-hypervisor-firmware#187]
We tried to start the guest OS from spdk bdev with this firmware, but failed because the EFI partition could not be found. If we change the queue length of the vhost user block to 16, we can find the EFI partition and read the bootloader, but during OS startup, reset vhost owner will cause the spdk backend to crash.

**Comment by rbradford** [comment]
@maydaycc Thank you for taking the time to make a bug report. There are however quite a lot of details lacking to make it useful. I would point out that rust-hypervisor-firmware has a hardcoded queue size of 16. The virtio spec specifies that the queue size advertised is a maximum and the guest side is allowed to use a smaller queue size. What queue size were you using that was failing?

**Comment by rbradford** [comment]
Issue was addressed in Cloud Hypervisor: https://github.com/cloud-hypervisor/cloud-hypervisor/pull/4286
