### ISSUE TITLE
Bump version

### ISSUE THREAD

**Issue by edigaryev** [cloud-hypervisor/rust-hypervisor-firmware#295]
The latest [`0.4.2` release](https://github.com/cloud-hypervisor/rust-hypervisor-firmware/releases/tag/0.4.2) was exactly a year ago, and there were [`147` commits](https://github.com/cloud-hypervisor/rust-hypervisor-firmware/compare/0.4.2...main) made since then.

It would be nice to have a new version cut, so people could try the Rust Hypervisor Firmware for `aarch64` and all the other features and bug fixes.

**Comment by edigaryev** [comment]
@rbradford would you mind taking a look at this?

Thanks in advance!

**Comment by edigaryev** [comment]
@rbradford just a friendly nudge! 👉 👈

It's been 2 years since the last `0.4.2` release, many important bugfixes were merged into the `main`. Any chance we can have a new version released?

Or, perhaps, is there something that the community can help with to make this happen?

**Comment by retrage** [comment]
@rbradford Sure! I created #356.
