### ISSUE TITLE
Remove Linux Boot Protocol Support

### ISSUE THREAD

**Issue by josephlr** [cloud-hypervisor/rust-hypervisor-firmware#47]
Is this something that we want to keep around long-term?

Right now we only support this because CH used to require it, but now both CH and this firmware support PVH. Also, unlike PVH, our final binary doesn't advertise support for the Linux Boot Protocol (i.e. we don't have the right header+magic bits), so it seems strange that we implement it by blindly assuming that anything that uses the main 64-bit ELF entry point expects us to be Linux.

**Comment by josephlr** [comment]
The only reason I can think to keep it is for compatibility w/ firecracker or crosvm

**Comment by rbradford** [comment]
I think we can remove it.
