### ISSUE TITLE
Work out how to mitigate "nightly" risks

### ISSUE THREAD

**Issue by rbradford** [cloud-hypervisor/rust-hypervisor-firmware#7]
Nightly doesn't have clippy at the moment so the CI has currently failed. Although it's possible to fix on a particular version of nightly (via rust-toolchain) that sometimes goes wrong as it pulls down the latest rust-src which might not compile with that compiler.

@joshtriplett do you have any thoughts on how we could move away from nightly or mitigate the risks? A docker container with a known good toolchain already installed?

**Comment by josephlr** [comment]
I think the best way to handle this would be to use a preinstalled docker container (Cirrus CI has good workflows for that). Then you could also stop downloading the Clear Linux image on each CI run.

I can take a look at this, we did a similar thing for [go-tpm](https://github.com/google/go-tpm) see https://github.com/google/go-tpm/pull/126

**Comment by rbradford** [comment]
A container sounds like a fine idea. I think it might still be a good idea to keep a fixed toolchain in the repo (and container I guess, too) and that's just simply some of the nightly builds are better than others in that they contain valuable tools such as RLS. However moving it forward more frequently as you did recently is also something that needs to be done.

**Comment by retrage** [comment]
@rbradford @josephlr I noticed that this issue has been fixed with containerized build and tests. Is it OK to close this issue?

**Comment by rbradford** [comment]
Yup. Sounds good. Thanks for the triage @retrage.
